# Generated by Django 4.1.6 on 2023-02-10 11:14

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_alter_youtubers_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubers',
            name='camera_type',
            field=models.CharField(choices=[('canon', 'canon'), ('nikon', 'nikon'), ('fuji', 'fuji')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtubers',
            name='category',
            field=models.CharField(choices=[('coder', 'coder'), ('cocking', 'cocking'), ('comedy', 'comedy')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtubers',
            name='crew',
            field=models.CharField(choices=[('solo', 'solo'), ('small', 'small'), ('medium', 'medium')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtubers',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
