# Generated by Django 4.1.6 on 2023-02-10 11:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0003_alter_youtubers_camera_type_alter_youtubers_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubers',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
